// Jasmine Leek
// 20 oct 2022
// Mini Challenge 8 "Guess It"
// This is a program that allows the user to guess a number randomly generated by the 
// computer in 3 game modes (easy 1-10, medium 1-50, hard 1-100)


//declare variables
int easyLvl = 10;
int medLvl = 50;
int hardLvl = 100;
int winNum = 0;
int userGuess = 0;
int guessCount = 0;

string userMode;
string userNum;
string playAgain = "yes";

bool validNum = false;
bool isCorrectGuess = false;

Console.Clear();

while (playAgain == "yes" || playAgain == "Yes" || playAgain == "YES")
{

    //choose game mode
    Console.WriteLine("Let's play Guess It! There are three difficulty levels: ");
    Console.WriteLine("");
    Console.WriteLine("Easy: guess a number between 1 - 10");
    Console.WriteLine("Medium: guess a number between 1 - 50");
    Console.WriteLine("Hard: guess a number between 1 - 100\n");
    Console.WriteLine("Select a game mode: Easy, Medium, or Hard?");
    userMode = Console.ReadLine().ToLower();

    while (userMode != "easy" && userMode != "medium" && userMode != "hard")
    {
        Console.WriteLine("Oops, that's not an option, please try again. Select a game mode: Easy, Medium, or Hard?");
        userMode = Console.ReadLine();
        userMode = userMode.ToLower();
    }

    Console.WriteLine($"You selected {userMode} mode!");

    //declare random number
    Random random = new Random();

    //for game mode: easy
    if (userMode == "easy")
    {
        winNum = random.Next(1, easyLvl + 1);

        Console.WriteLine("Try to guess the computer's number! Enter a number 1-10");


        while (isCorrectGuess == false)
        {
            userNum = Console.ReadLine();
            validNum = Int32.TryParse(userNum, out userGuess);
            while (validNum == false)
            {

                if (validNum == false)
                {
                    Console.WriteLine("Please enter a valid number.");
                    userNum = Console.ReadLine();
                    validNum = Int32.TryParse(userNum, out userGuess);
                }

            }
            if (userGuess > winNum)
            {
                ++guessCount;
                Console.WriteLine("Too high! Try again!");
                // userGuess = Convert.ToInt32(Console.ReadLine());
            }
            else if (userGuess < winNum)
            {
                Console.WriteLine("Too low! Try again!");
                ++guessCount;
                // userGuess = Convert.ToInt32(Console.ReadLine());
            }
            else
            {
                Console.WriteLine("Correct!");
                ++guessCount;
                Console.WriteLine("You solved it in " + guessCount + " attempts.");
                isCorrectGuess = true;
            }


        }

    }
    //for game mode: medium
    else if (userMode == "medium")
    {
        winNum = random.Next(1, medLvl + 1);

        Console.WriteLine("Try to guess the computer's number! Enter a number 1-50");


        while (isCorrectGuess == false)
        {
            userNum = Console.ReadLine();
            validNum = Int32.TryParse(userNum, out userGuess);
            while (validNum == false)
            {

                if (validNum == false)
                {
                    Console.WriteLine("Please enter a valid number.");
                    userNum = Console.ReadLine();
                    validNum = Int32.TryParse(userNum, out userGuess);
                }

            }
            if (userGuess > winNum)
            {
                ++guessCount;
                Console.WriteLine("Too high! Try again!");
                // userGuess = Convert.ToInt32(Console.ReadLine());
            }
            else if (userGuess < winNum)
            {
                Console.WriteLine("Too low! Try again!");
                ++guessCount;
                // userGuess = Convert.ToInt32(Console.ReadLine());
            }
            else
            {
                Console.WriteLine("Correct!");
                ++guessCount;
                Console.WriteLine("You solved it in " + guessCount + " attempts.");
                isCorrectGuess = true;
            }


        }

    }
    //for game mode: hard
    else if (userMode == "hard")
    {
        winNum = random.Next(1, hardLvl + 1);

        Console.WriteLine("Try to guess the computer's number! Enter a number 1-100");


        while (isCorrectGuess == false)
        {
            userNum = Console.ReadLine();
            validNum = Int32.TryParse(userNum, out userGuess);
            while (validNum == false)
            {

                if (validNum == false)
                {
                    Console.WriteLine("Please enter a valid number.");
                    userNum = Console.ReadLine();
                    validNum = Int32.TryParse(userNum, out userGuess);
                }

            }
            if (userGuess > winNum)
            {
                ++guessCount;
                Console.WriteLine("Too high! Try again!");
                // userGuess = Convert.ToInt32(Console.ReadLine());
            }
            else if (userGuess < winNum)
            {
                Console.WriteLine("Too low! Try again!");
                ++guessCount;
                // userGuess = Convert.ToInt32(Console.ReadLine());
            }
            else
            {
                Console.WriteLine("Correct!");
                ++guessCount;
                Console.WriteLine("You solved it in " + guessCount + " attempts.");
                isCorrectGuess = true;
            }


        }

    }
//ask user to play again
    Console.WriteLine("Play again? Type 'yes' to play again or enter any key to exit.");
    playAgain = Console.ReadLine();
    if (playAgain.ToLower() == "yes")
    {
        isCorrectGuess = false;
        guessCount = 0;
    }

}